application: ostblogging
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /fonts
  static_dir: static/fonts

- url: /images
  static_dir: static/images

- url: .*
  script: ostblogging.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name:    PIL
  version: latest
