application: ost-blogging
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static_files/css

- url: /fonts
  static_dir: static_files/fonts

-url: /js
  static_dir: static_files/js

- url: .*
  script: ost-blogging.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
